### ISSUE TITLE
The artifacts haven't published to the central maven repo

### ISSUE THREAD

**Issue by jecofang01** [apache/shardingsphere-plugin#21]
Hi guys,
Seems like the artifacts haven't published to the central maven repo. I can't find them either in https://central.sonatype.com/ or https://mvnrepository.com/

![image](https://github.com/apache/shardingsphere-plugin/assets/2755216/bad7cdcc-49d6-4ca6-a6b9-7c8af31c75c8)

**Comment by linghengqian** [comment]
> I see, you should clone this repository and install locally to generate the corresponding artifact to your m2 or nexus.
> 

- @taojintianxia This issue has not been closed yet because a PR with maven deploy plugin is required?

**Comment by Yule-Momoko** [comment]
Local install is also problematic

**Comment by linghengqian** [comment]
> Local install is also problematic

@Yule-Momoko Try https://github.com/apache/shardingsphere-plugin/tree/5.4.1.1 .

**Comment by Yule-Momoko** [comment]
> > 本地安装也有问题
> 
> @Yule-Momoko尝试https://github.com/apache/shardingsphere-plugin/tree/5.4.1.1。

Console output only：
com.zaxxer.hikari.HikariDataSource       : HikariPool-1 - Starting...

Do you need any more configuration?

application.properties:
spring.datasource.driver-class-name=org.apache.shardingsphere.driver.ShardingSphereDriver
spring.datasource.url=jdbc:shardingsphere:classpath:sharding.yaml

sharding.yaml:
mode:
  type: Cluster
  repository:
    type: nacos
    props:
      namespace: xxxx
      server-lists: xxxx:8848
      username: xxx
      password: xxx
      retryIntervalMilliseconds: 500
      timeToLiveSeconds: 60

**Comment by linghengqian** [comment]
> > > 本地安装也有问题
> > 
> > @Yule-Momoko尝试https://github.com/apache/shardingsphere-plugin/tree/5.4.1.1。
> 
> Console output only：
> com.zaxxer.hikari.HikariDataSource       : HikariPool-1 - Starting...
> 
> Do you need any more configuration?
> 
> application.properties:
> spring.datasource.driver-class-name=org.apache.shardingsphere.driver.ShardingSphereDriver
> spring.datasource.url=jdbc:shardingsphere:classpath:sharding.yaml
> 
> sharding.yaml:
> mode:
>   type: Cluster
>   repository:
>     type: nacos
>     props:
>       namespace: xxxx
>       server-lists: xxxx:8848
>       username: xxx
>       password: xxx
>       retryIntervalMilliseconds: 500
>       timeToLiveSeconds: 60

- The fix for 5.4.1.1 has not yet reached the master branch, I think you will have to open a new issue and write a unit test via testcontainers-java. 

- Background note, I have not investigated nacos.
