### ISSUE TITLE
maven cannot find shardingsphere-plugin-mode-cluster-repository-nacos

### ISSUE THREAD

**Issue by Yule-Momoko** [apache/shardingsphere-plugin#23]
maven cannot find shardingsphere-plugin-mode-cluster-repository-nacos

**Comment by RaigorJiang** [comment]
Yes, we need to compile the shardingsphere-plugin project locally, the plugin will not be published to maven.

**Comment by strongduanmu** [comment]
Since this issue has been resolved, I will close this issue.
