### ISSUE TITLE
shardingsphere-infra-algorithm-key-generator-core not found in maven repo.

### ISSUE THREAD

**Issue by zzyReal666** [apache/shardingsphere-plugin#36]
Hi!

Dependency `shardingsphere-infra-algorithm-key-generator-core` not found in maven repo:

![image](https://github.com/apache/shardingsphere-plugin/assets/34822229/6e996fa6-6839-4558-b34c-e545a08af570)

![image](https://github.com/apache/shardingsphere-plugin/assets/34822229/dbb286dc-15d2-46b8-9b1f-82765fffc49e)

**Comment by strongduanmu** [comment]
Please execute `mvn clean install -Prelease -Dmaven.javadoc.skip=true -Djacoco.skip=true -T 1C -Drat.skip=true` in ShardingSphere repository. Since this is a new module, you can't get it from mvn central repository now.

**Comment by zzyReal666** [comment]
I don not pull latest code , `shardingsphere-infra-algorithm-key-generator-core`has already rename to `shardingsphere-infra-key-generator-core`
