### ISSUE TITLE
Use AlgorithmInitializationException on sharding plugin's algorithm

### ISSUE THREAD

**Issue by strongduanmu** [apache/shardingsphere-plugin#42]
Since the ShardingSphere repository has deleted ShardingPluginException and replaced it with the new AlgorithmInitializationException exception, the Plugin repository needs to be modified synchronously.

After the modification is completed, please execute `./mvnw clean install -DskipITs -DskipTests -Prelease` to test.

**Comment by TherChenYang** [comment]
Please assign this issue to me, and I will try to handle it.

**Comment by strongduanmu** [comment]
@TherChenYang Welcome, I just assign it to you.

**Comment by TherChenYang** [comment]
@strongduanmu I have already submitted the corresponding PR. If you have time, please help review it. Thank you very much.
